import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { ClerkProvider } from '@clerk/nextjs'

import './globals.css'

import { Toaster } from '@/components/ui/sonner'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

const openSans = localFont({
  src: '/fonts/OpenSans-VariableFont_wdth,wght.ttf',
  preload: false
})

//👇 Configure the object for our second font
const roboto = localFont({
  src: '/fonts/Roboto-VariableFont_wdth,wght.ttf',
  preload: false
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang='en' suppressHydrationWarning>
        <body
          className={`${openSans.className} ${roboto.className} bg-gray-100 font-sans antialiased`}
        >
          <Header />
          {children}
          <Toaster
            position='bottom-center'
            toastOptions={{
              unstyled: true,
              classNames: {
                error: 'bg-red-600',
                success: 'text-green-700',
                warning: 'text-yellow-700',
                info: 'bg-blue-700'
              }
            }}
          />
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  )
}
